CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  image LONGBLOB
);

ALTER TABLE products
ADD COLUMN parent_id INT DEFAULT NULL,
ADD CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES products(id);
